language: node_js

node_js:
  - "stable"

sudo: false

before_script:
  - npm install

install:
  - npm install -g codecov
  
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov